substitutions:
  rotary_pin_a: "21"
  rotary_pin_b: "22"
  
sensor:
  - platform: rotary_encoder
    filters:
    - throttle: 0.01s
    name: "Rotary Encoder"
    internal: true
    pin_a:
      number: $rotary_pin_a
      mode:
        input: true
        pullup: true
    pin_b:
      number: $rotary_pin_b
      mode:
        input: true
        pullup: true
    id: rotary
    on_clockwise:
      - lambda: |-
          id(homeThingMenu)->buttonPressWakeUpDisplay();
          id(homeThingMenu)->rotaryScrollClockwise(id(rotary).state);
    on_anticlockwise:
      - lambda: |-
          id(homeThingMenu)->buttonPressWakeUpDisplay();
          id(homeThingMenu)->rotaryScrollCounterClockwise(id(rotary).state);