esphome:
  name: "homething-lilygo"
  platform: ESP32
  board: featheresp32

external_components:
  - source:
      type: git
      url: https://github.com/landonr/homeThing
      ref: lando/codeCleanup
    refresh: 0s
    components: [ 
      homeassistant_switch_group, 
      homeassistant_sensor_group,
      homeassistant_light_group,
      homeassistant_media_player,
      homeassistant_service_group,
      homeThing,
    ]

#leave this to include default ipod controls
packages:
  remote_package:
    url: https://github.com/landonr/homeThing
    ref: lando/codeCleanup # optional
    files: [
      common/device_base.yaml, 
      common/ipod/lilygo_tdisplay_ipod_backlight.yaml,
      common/ipod/lilygo_tdisplay_ipod_battery.yaml,
      common/ipod/lilygo_tdisplay_ipod_binary_sensor.yaml,
      common/ipod/lilygo_tdisplay_ipod_rotary.yaml,
      common/ipod/lilygo_tdisplay_ipod_sleep.yaml,
      common/ipod/lilygo_tdisplay_ipod_switch.yaml,
      common/fonts.yaml,
      common/icon_fonts.yaml
    ]
    refresh: 0s
  setup: !include homeConfig/device_setup.yaml

# customize these

# switch menu
switch:
  # replace with your switchs
    - platform: homeassistant_switch_group
      entity_id: "switch.oven_fan"
      name: "Oven Fan"
      id: oven_fan_switch

homeassistant_switch_group:
  # defined above with switches
  id: switch_group_component
  switches:
    - id: "oven_fan_switch"

# sensor menu
text_sensor:
  - platform: homeassistant
    entity_id: "sensor.vancouver_forecast"
    name: ""
    id: sensor_weather

homeassistant_sensor_group:
  id: sensor_group_component
  sensors:
    - id: sensor_weather

# light menu
light:
  - platform: homeassistant_light_group
    id: light_office_lamp
    entity_id: light.office_lamp
    name: Office Lamp

homeassistant_light_group:
  id: light_group_component
  lights:
    - id: light_office_lamp

# media player menu
media_player:
  - platform: homeassistant_media_player
    name: Beam
    entity_id: "media_player.beam"
    id: media_player_beam
    type: speaker
  - platform: homeassistant_media_player
    name: TV
    entity_id: "media_player.55_tcl_roku_tv"
    id: media_player_tv
    type: roku
    soundbar:
      speaker: media_player_beam

homeassistant_media_player:
  id: media_group_component
  media_players:
    - id: media_player_beam
      type: speaker
    - id: media_player_tv
      type: roku

# service menu
homeassistant_service_group:
  id: service_group_component
  commands:
    - text: "desk nudge up"
      command:
        - lambda: |-
            ESP_LOGI("homeassistant_service_group", "nudge up");
        - homeassistant.service:
            service: button.press
            data:
              entity_id: "button.desk_position_nudge_up"

homeThing:
  id: homeThingMenu
  sleep_switch: sleep_toggle
  backlight: backlight
  battery:
    battery_percent: battery_percent
    charging: charging
  media_player_group: media_group_component
  light_group: light_group_component
  service_group: service_group_component
  sensor_group: sensor_group_component
  switch_group: switch_group_component
  display: my_display
  on_redraw:
    then:
      component.update: my_display
  display_state:
    draw_battery_level: true
    font_small: small_font
    font_medium: medium_font
    font_large: large_font
    font_large_heavy: large_heavy_font
    font_material_large: material_font_large
    font_material_small: material_font_small
    font_logo: home_thing_logo

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

display:
  - platform: st7789v
    model: TTGO_TDisplay_135x240
    id: my_display
    backlight_pin: GPIO4
    cs_pin: GPIO5
    dc_pin: GPIO16
    reset_pin: GPIO23
    rotation: 90
    update_interval: 10s
    lambda: |-
      id(homeThingMenu)->draw_menu_screen();
      return;
