esphome:
  name: fireremote
  platform: ESP32
  board: m5stack-fire
  includes:
    - esphomeRemote/MenuGlobals.h
    - esphomeRemote/MenuTitle.h
    - esphomeRemote/esphomeRemotePlayer.h
    - esphomeRemote/esphomeRemoteService.h
    - esphomeRemote/esphomeRemoteLight.h
    - esphomeRemote/esphomeRemoteSensor.h
    - esphomeRemote/DisplayUpdateInterface.h
    - esphomeRemote/esphomeRemote.h
    - esphomeRemote/esphomeRemoteNowPlayingMenu.h
    - esphomeRemote/esphomeRemote3Button.h
    - esphomeRemote/esphomeRemoteFireLight.h

substitutions:
  boot_name: '"Fire Remote <3"'
  friendly_name: "M5Fire Remote"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_fallback_password: !secret wifi_fallback_password
  large_font_size: "24"
  medium_font_size: "20"
  small_font_size: "18"
  icon_size: "24"
  icon_size_large: "28"
  header_height: "24"
  margin_size: "8"
  scroll_bar_width: "8"
  bottom_bar_margin: "42"
  now_playing_max_lines: "5"
  draw_now_playing_menu: "true"
  draw_battery_level: "true"
  draw_volume_level: "false"
  draw_shuffle_disabled: "false"
  color_accent_primary_red: 63%
  color_accent_primary_green: 13%
  color_accent_primary_blue: 94%
  display_timeout: "16"
  sleep_after: "7200"

<<: !include esphomeRemote/sharedRemoteConfig.yaml

external_components:
  - source:
      type: git
      url: https://github.com/ssieb/custom_components
    components: [ ip5306 ]

i2c:
  sda: 21
  scl: 22
  scan: True

ip5306:
  battery_level:
    name: ${friendly_name} Battery Percent
    id: batteryPercent
    on_value :
      then:
        - lambda: |-
            if(id(batteryPercent).state > previousBatteryLevel && !charging) {
                charging = true;
            } else if(id(batteryPercent).state <= previousBatteryLevel && charging) {
                charging = false;
            }
            previousBatteryLevel = id(batteryPercent).state;
  charger_connected:
    internal: true
    id: connected
    on_press:
      then:
        - lambda: |-
            ESP_LOGD("TEST", "charging");
            if (charging == false) {
              charging = true;
            }
        
    on_release:
      then:
        - lambda: |-
            ESP_LOGD("TEST", "not charging");
            if (charging == true) {
              charging = false;
            }
  charge_full:
    id: full
    internal: true
    on_press:
      then:
        - lambda: ESP_LOGD("TEST", "fully charged");
    on_release:
      then:
        - lambda: ESP_LOGD("TEST", "still charging");

deep_sleep:
  id: deep_sleep_fire
  wakeup_pin: 39
  wakeup_pin_mode: INVERT_WAKEUP

binary_sensor:
  - platform: gpio
    id: M5_BtnA
    pin:
      number: 39
      inverted: true
    on_click:
      then:
        - lambda: |-
            buttonPressLeft();
  - platform: gpio
    id: M5_BtnB
    pin:
      number: 38
      inverted: true
    on_click:
      then:
        - lambda: |-
            buttonPressSelect();
  - platform: gpio
    id: M5_BtnC
    pin:
      number: 37
      inverted: true
    on_click:
      then:
        - lambda: |-
            buttonPressRight();

# We can still control the backlight independently
switch:
  - platform: template
    name: ${friendly_name} Sleep Toggle
    id: sleep_toggle
    optimistic: true
    on_turn_on:
      then:
        - deep_sleep.enter:
            id: deep_sleep_fire
  - platform: gpio
    pin: 32
    name: ${friendly_name} Backlight
    id: backlight
    restore_mode: ALWAYS_ON
    internal: true

light:
  - platform: fastled_clockless
    chipset: SK6812
    pin: GPIO15
    num_leds: 10
    rgb_order: GRB
    id: side_light
    name: ${friendly_name} Remote Light"
    restore_mode: ALWAYS_OFF
    default_transition_length: 0s
    effects:
      - addressable_rainbow:
          name: Rainbow Effect
          speed: 20
          width: 15

spi:
  clk_pin: 18
  mosi_pin: 23
  miso_pin: 19

display:
  - platform: ili9341
    model: M5STACK
    cs_pin: 14
    dc_pin: 27
    led_pin: 32  ### see note below ###
    reset_pin: 33
    id: my_display
    update_interval: 10s
    lambda: |-
      manageLight();
      if (idleTime < 0) {
        ESP_LOGD("drawing menu", "turning on");
        id(backlight).turn_on();
        idleTime = 0;
      }
      drawMenu();
      return;
      
