esphome:
  name: m5stickc
  includes:
    - homeThing/MenuGlobals.h
    - homeThing/MenuTitle.h
    - homeThing/FriendlyNameEntity.h
    - homeThing/TextHelpers.h
    - homeThing/DisplayUpdateInterface.h
    - homeThing/esphomeRemote.h
    - homeThing/esphomeRemoteNowPlayingMenu.h
    - homeThing/esphomeRemote2Button.h
    - homeThing/esphomeRemoteCommon.h

esp32:
  board: m5stick-c
  framework:
    type: arduino

substitutions:
  boot_name: '"M5Stick Remote <3"'
  boot_logo_size: "48"
  friendly_name: M5stickcRemote
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_fallback_password: !secret wifi_fallback_password
  large_font_size: "20"
  medium_font_size: "14"
  small_font_size: "12"
  icon_size: "18"
  icon_size_large: "19"
  header_height: "16"
  margin_size: "4"
  slider_margin_size: "6"
  scroll_bar_width: "6"
  bottom_bar_margin: "32"
  now_playing_max_lines: "8"
  draw_now_playing_menu: "true"
  draw_battery_level: "true"
  draw_volume_level: "false"
  draw_shuffle_disabled: "false"
  draw_header_time: "false"
  color_accent_primary_red: 63%
  color_accent_primary_green: 13%
  color_accent_primary_blue: 94%
  display_timeout: "16"
  sleep_after: "7200"
  menu_rollover_on: "false"
  sync_active_player: "true"
  dec_brightness_step: "10"
  inc_brightness_step: "10"
  dec_color_temperature_step: "10"
  inc_color_temperature_step: "10"
  dark_mode: "true"
  keep_states_in_sync: "false"

<<: !include homeThing/sharedRemoteConfig.yaml

i2c:
   - id: bus_a
     sda: GPIO21
     scl: GPIO22
     scan: true

external_components:
  - source:
      type: git
      url: https://gitlab.com/geiseri/esphome_extras.git
    refresh: 0s
    components: [axp192]
  - <<: !include homeThing/sharedExternalComponents.yaml

axp192:
  id: axp
  address: 0x34
  update_interval: 60s
  charge_voltage: 4150mV
  dcdc1_voltage: 3300mv
  dcdc3_voltage: 1.5V

text_sensor:
  !include homeThing/sharedTextSensors.yaml

sensor:
    # AXP192 power management - must be present to initialize TFT power on
  - platform: axp192
    axp192_id: axp
    id: batteryPercent
    type: battery_power
  - platform: template
    id: display_update_tick
    filters:
      - debounce: 0.02s
    on_value :
      then:
        - lambda: |-
            if(idleTime < 2) {
              displayUpdate.updateDisplay(true);
            }
# internal LED
light:
  - platform: homeassistant_light_group
    id: light_bathroom_lights
    entity_id: light.bathroom_lights
    name: Bathroom 
  - platform: homeassistant_light_group
    id: light_bedroom_lights
    entity_id: light.bedroom_lights
    name: Bedroom 
  - platform: homeassistant_light_group
    id: light_kitchen_lights
    entity_id: light.kitchen_lights
    name: Kitchen 
  - platform: homeassistant_light_group
    id: light_living_room_lights
    entity_id: light.living_room_lights
    name: Living Room 
  - platform: homeassistant_light_group
    id: light_office_lamp
    entity_id: light.office_lamp
    name: Office Lamp
  - platform: monochromatic
    output:  builtin_led
    name: Led
    id: led1
    internal: True
  - platform: monochromatic
    output: axp_ldo3
    restore_mode: ALWAYS_ON
    name: "Backlight"
    id: axpbacklight
    internal: True

output:
  - platform: ledc
    pin: 10
    inverted: true
    id: builtin_led
  - platform: axp192
    axp192_id: axp
    output: ldo3
    id: axp_ldo3  

binary_sensor:
  - platform: axp192
    axp192_id: axp
    type: charge_indicate
    id: axp_charger
    name: "Charger"
    on_state:
      then:
        lambda: |-
          charging = x;
  - platform: gpio
    pin:
      number: GPIO37
      inverted: true
    name: Button A
    on_press:
      then:
        lambda: |-
            buttonPressRight();
            auto call = id(led1).turn_on();
            call.set_transition_length(0);
            call.perform();
    on_release:
      then:
        - light.turn_off: led1
        
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: Button B
    on_press:
      then:
        lambda: |-
            buttonPressSelect();
            auto call = id(led1).turn_on();
            call.set_transition_length(0);
            call.perform();
    on_release:
      then:
        - light.turn_off: led1

deep_sleep:
  id: deep_sleep_m5
  wakeup_pin: 37
  wakeup_pin_mode: INVERT_WAKEUP

switch:
  - platform: homeassistant_switch_group
    entity_id: "switch.oven_fan"
    name: "Oven Fan"
    id: oven_fan_switch
  - platform: axp192
    axp192_id: axp
    output: ldo3
    name: LDO3
  - platform: template
    id: sleep_toggle
    internal: true
    optimistic: true
    on_turn_on:
      then:
        - light.turn_off:
            id: axpbacklight
            transition_length: 0s
        - delay: 0.5s
        - deep_sleep.enter:
            id: deep_sleep_m5
  - platform: template
    id: backlight
    optimistic: true
    internal: true
    on_turn_on:
      then:
        - light.turn_on:
            id: axpbacklight
    on_turn_off:
      then:
        - light.turn_off:
            id: axpbacklight
            transition_length: 0.5s

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO15

display:
  - platform: st7789v
    model: TTGO_TDisplay_135x240
    id: my_display
    cs_pin: GPIO5
    dc_pin: GPIO23
    reset_pin: GPIO18
    rotation: 0
    update_interval: 3600s
    lambda: |-
      if (idleTime < 0) {
        ESP_LOGD("drawing menu", "turning on");
        id(backlight).turn_on();
        idleTime = 0;
      }

      drawMenu();
      return;
