esphome:
  name: m5stickc

esp32:
  board: m5stick-c
  framework:
    type: arduino

i2c:
  - id: bus_a
    sda: GPIO21
    scl: GPIO22
    scan: true

external_components:
 - source:
     type: git
     url: https://gitlab.com/geiseri/esphome_extras.git
   refresh: 0s
   components: [axp192]
 - source:
   #   type: git
   #   url: https://github.com/landonr/homeThing
   #   ref: lando/codeCleanup
   # refresh: 0s
     type: local
     path: components
   components: [ 
     homeassistant_switch_group, 
     homeassistant_sensor_group,
     homeassistant_light_group,
     homeassistant_media_player,
     homeassistant_service_group,
     homeThing,
   ]


packages:
  device_base: !include common/device_base.yaml
  setup: !include homeConfig/device_setup.yaml
  home_media_player: !include homeConfig/media_player.yaml
  home_text_sensor: !include homeConfig/text_sensor.yaml
  home_light: !include homeConfig/light.yaml
  home_switch: !include homeConfig/switch.yaml
  menu_group: !include homeConfig/menu_group.yaml

font:
## Font needs to be monospace!
  - file: "fonts/iosevka-heavy.ttf"
    id: large_heavy_font
    size: 24
    glyphs: '^…*/|\$#<>!?"%()[]+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz&êÊîÎâÂôÔéÉíÍáÁóÓëËüÜïÏöÖøØṣṢñãõÑÃÕ''’'
  - file: "fonts/iosevka.ttf"
    id: large_font
    size: 24
    glyphs: '^…*/|\$#<>!?"%()[]+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz&êÊîÎâÂôÔéÉíÍáÁóÓëËüÜïÏöÖøØṣṢñãõÑÃÕ''’'
  - file: "fonts/iosevka.ttf"
    id: medium_font
    size: 15
    glyphs: '^…*/|\$#<>!?"%()[]+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz&êÊîÎâÂôÔéÉíÍáÁóÓëËüÜïÏöÖøØṣṢñãõÑÃÕ''’'
  - file: "fonts/iosevka.ttf"
    id: small_font
    size: 14
    glyphs: '^…*/|\$#<>!?"%()[]+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz&êÊîÎâÂôÔéÉíÍáÁóÓëËüÜïÏöÖøØṣṢñãõÑÃÕ''’'
  - file: 'fonts/homeThingFontLogo.ttf' 
    id: home_thing_logo
    size: 48
    glyphs: [
      '',
    ]  
  - file: 'fonts/materialdesignicons-webfont.ttf' 
    id: material_font_large
    size: 19
    glyphs: [
      '󰐊', # mdi-play
      '󰓛', # mdi-stop
      '󰏤', # home-pause
      '󰽥', # mdi-moon-waning-crescent
      '󰒝', # mdi-shuffle
      '󰒞', # mdi-shuffle-disabled
      '󰕾', # mdi-volume-high
      '󰕿', # mdi-volume-low
      '󰚺', # mdi-plex
      '󰝆', # mdi-netflix
      '󰗃', # mdi-youtube
      '󰓇', # mdi-spotify
      '󰔂', # mdi-television
      '󰋜', # mdi-home
      '󰌵', # mdi-lightbulb
      '󰌶', # mdi-lightbulb-outline
    ]  
  - file: 'fonts/materialdesignicons-webfont.ttf' 
    id: material_font_small
    size: 18
    glyphs: [
      '󰐊', # mdi-play
      '󰓛', # mdi-stop
      '󰏤', # home-pause
      '󰽥', # mdi-moon-waning-crescent
      '󰒝', # mdi-shuffle
      '󰒞', # mdi-shuffle-disabled
      '󰕾', # mdi-volume-high
      '󰕿', # mdi-volume-low
      '󰚺', # mdi-plex
      '󰝆', # mdi-netflix
      '󰗃', # mdi-youtube
      '󰓇', # mdi-spotify
      '󰔂', # mdi-television
      '󰋜', # mdi-home
      '󰌵', # mdi-lightbulb
      '󰌶', # mdi-lightbulb-outline
    ]

axp192:
 id: axp
 address: 0x34
 update_interval: 60s
 charge_voltage: 4150mV
 dcdc1_voltage: 3300mv
 dcdc3_voltage: 1.5V

sensor:
   # AXP192 power management - must be present to initialize TFT power on
 - platform: axp192
   axp192_id: axp
   id: batteryPercent
   type: battery_power

# internal LED
light:
 - platform: monochromatic
   output:  builtin_led
   name: Led
   id: led1
   internal: True
 - platform: monochromatic
   output: axp_ldo3
   restore_mode: ALWAYS_ON
   name: "Backlight"
   id: axpbacklight
   internal: True

output:
 - platform: ledc
   pin: 10
   inverted: true
   id: builtin_led
 - platform: axp192
   axp192_id: axp
   output: ldo3
   id: axp_ldo3  

binary_sensor:
 - platform: axp192
   axp192_id: axp
   type: charge_indicate
   id: axp_charger
   name: "Charger"
   on_state:
     then:
       lambda: |-
        //  charging = x;
 - platform: gpio
   pin:
     number: GPIO37
     inverted: true
   name: Button A
   on_press:
     then:
       lambda: |-
           id(homeThingMenu)->buttonPressRight();
           auto call = id(led1).turn_on();
           call.set_transition_length(0);
           call.perform();
   on_release:
     then:
       - light.turn_off: led1
       
 - platform: gpio
   pin:
     number: GPIO39
     inverted: true
   name: Button B
   on_press:
     then:
       lambda: |-
           id(homeThingMenu)->buttonPressSelect();
           auto call = id(led1).turn_on();
           call.set_transition_length(0);
           call.perform();
   on_release:
     then:
       - light.turn_off: led1

deep_sleep:
 id: deep_sleep_
 wakeup_pin: 37
 wakeup_pin_mode: INVERT_WAKEUP

switch:
- platform: axp192
  axp192_id: axp
  output: ldo3
  name: LDO3
- platform: template
  id: sleep_toggle
  internal: true
  optimistic: true
  on_turn_on:
    then:
      - light.turn_off:
          id: axpbacklight
          transition_length: 0s
      - delay: 0.5s
      - deep_sleep.enter:
          id: deep_sleep_
- platform: template
  id: backlight
  optimistic: true
  internal: true
  on_turn_on:
    then:
      - light.turn_on:
          id: axpbacklight
  on_turn_off:
    then:
      - light.turn_off:
          id: axpbacklight
          transition_length: 0.5s

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO15

homeThing:
  id: homeThingMenu
  media_player_group: media_group_component
  light_group: light_group_component
  service_group: service_group_component
  sensor_group: sensor_group_component
  switch_group: switch_group_component
  display: my_display
  on_redraw:
    then:
      component.update: my_display
  display_state:
    font_small: small_font
    font_medium: medium_font
    font_large: large_font
    font_large_heavy: large_heavy_font
    font_material_large: material_font_large
    font_material_small: material_font_small
    font_logo: home_thing_logo
    draw_now_playing_bottom_menu: True

display:
  - platform: st7735
    model: "INITR_18BLACKTAB"
    id: my_display
    reset_pin: GPIO18
    cs_pin: GPIO5
    dc_pin: GPIO23
    rotation: 90
    device_width: 128
    device_height: 160
    col_start: 0
    row_start: 0
    eight_bit_color: true
    update_interval: 3600s    
    lambda: |-
      id(homeThingMenu)->draw_menu_screen();
      return;
