esphome:
  name: tdisplayt4

esp32:
  board: esp32dev
  framework:
    type: arduino

packages:
  device_base: !include common/device_base.yaml
  
font:
  ## Font needs to be monospace!
    - file: "fonts/iosevka-heavy.ttf"
      id: large_heavy_font
      size: 24
      glyphs: '^…*/|\$#<>!?"%()[]+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz&êÊîÎâÂôÔéÉíÍáÁóÓëËüÜïÏöÖøØṣṢñãõÑÃÕ''’'
    - file: "fonts/iosevka.ttf"
      id: large_font
      size: 22
      glyphs: '^…*/|\$#<>!?"%()[]+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz&êÊîÎâÂôÔéÉíÍáÁóÓëËüÜïÏöÖøØṣṢñãõÑÃÕ''’'
    - file: "fonts/iosevka.ttf"
      id: medium_font
      size: 20
      glyphs: '^…*/|\$#<>!?"%()[]+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz&êÊîÎâÂôÔéÉíÍáÁóÓëËüÜïÏöÖøØṣṢñãõÑÃÕ''’'
    - file: "fonts/iosevka.ttf"
      id: small_font
      size: 18
      glyphs: '^…*/|\$#<>!?"%()[]+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz&êÊîÎâÂôÔéÉíÍáÁóÓëËüÜïÏöÖøØṣṢñãõÑÃÕ''’'
    - file: 'fonts/homeThingFontLogo.ttf' 
      id: home_thing_logo
      size: 64
      glyphs: [
        '',
      ]  
    - file: 'fonts/materialdesignicons-webfont.ttf' 
      id: material_font_large
      size: 28
      glyphs: [
        '󰐊', # mdi-play
        '󰓛', # mdi-stop
        '󰏤', # home-pause
        '󰽥', # mdi-moon-waning-crescent
        '󰒝', # mdi-shuffle
        '󰒞', # mdi-shuffle-disabled
        '󰕾', # mdi-volume-high
        '󰕿', # mdi-volume-low
        '󰚺', # mdi-plex
        '󰝆', # mdi-netflix
        '󰗃', # mdi-youtube
        '󰓇', # mdi-spotify
        '󰔂', # mdi-television
        '󰋜', # mdi-home
        '󰌵', # mdi-lightbulb
        '󰌶', # mdi-lightbulb-outline
      ]  
    - file: 'fonts/materialdesignicons-webfont.ttf' 
      id: material_font_small
      size: 24
      glyphs: [
        '󰐊', # mdi-play
        '󰓛', # mdi-stop
        '󰏤', # home-pause
        '󰽥', # mdi-moon-waning-crescent
        '󰒝', # mdi-shuffle
        '󰒞', # mdi-shuffle-disabled
        '󰕾', # mdi-volume-high
        '󰕿', # mdi-volume-low
        '󰚺', # mdi-plex
        '󰝆', # mdi-netflix
        '󰗃', # mdi-youtube
        '󰓇', # mdi-spotify
        '󰔂', # mdi-television
        '󰋜', # mdi-home
        '󰌵', # mdi-lightbulb
        '󰌶', # mdi-lightbulb-outline
      ]

sensor:
  - platform: template
    name: Battery Percent
    id: batteryPercent
    unit_of_measurement: '%'

binary_sensor:
  - platform: gpio
    id: T4_BtnA
    pin:
      number: 39
      inverted: true
    on_click:
      then:
        - lambda: |-
            id(homeThingMenu)->rotaryScrollCounterClockwise(0);
  - platform: gpio
    id: T4_BtnB
    pin:
      number: 37
      inverted: true
    on_click:
      then:
        - lambda: |-
            id(homeThingMenu)->buttonPressSelect();
  - platform: gpio
    id: T4_BtnC
    pin:
      number: 38
      inverted: true
    on_click:
      then:
        - lambda: |-
            id(homeThingMenu)->rotaryScrollClockwise(0);

# We can still control the backlight independently
switch:
  - platform: gpio
    pin:
      number: 27
      inverted: false
    id: comb
    internal: true
  - platform: gpio
    pin:
      number: 26
      inverted: false
    id: coma
    internal: true
  - platform: gpio
    pin: GPIO4
    name: "Backlight"
    id: backlight
    internal: true
    restore_mode: RESTORE_DEFAULT_ON

spi:
  clk_pin: 18
  miso_pin: 12
  mosi_pin: 23

homeThing:
  id: homeThingMenu
  settings:
    mode: 3_button
  media_player_group: media_group_component
  light_group: light_group_component
  service_group: service_group_component
  sensor_group: sensor_group_component
  switch_group: switch_group_component
  display: my_display
  on_redraw:
    then:
      component.update: my_display
  display_state:
    font_small: small_font
    font_medium: medium_font
    font_large: large_font
    font_large_heavy: large_heavy_font
    font_material_large: material_font_large
    font_material_small: material_font_small
    font_logo: home_thing_logo
    header_height: 24
    margin_size: 8
    slider_margin_size: 6
    scroll_bar_width: 8
    bottom_bar_margin: 8
    now_playing_max_lines: 10
    draw_now_playing_bottom_menu: true
    dark_mode: true
    draw_volume_level: false
    draw_shuffle_disabled: false
    draw_header_time: true

display:
  - platform: ili9341
    id: my_display
    model: TFT_2.4
    cs_pin: 27
    dc_pin: 32
    led_pin: 04  ### see note below ###
    reset_pin: 05
    update_interval: 3600s
    rotation: 90
    lambda: |-
      id(homeThingMenu)->draw_menu_screen();
      return;