color:
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%
  - id: my_yellow
    red: 100%
    green: 75%
    blue: 10%
  - id: my_green
    red: 0%
    green: 100%
    blue: 0%
  - id: my_blue
    red: 0%
    green: 45%
    blue: 68%
  - id: my_gray_dark
    red: 40%
    green: 40%
    blue: 40%
  - id: my_gray_dark_2
    red: 8%
    green: 8%
    blue: 8%
  - id: my_gray
    red: 10%
    green: 10%
    blue: 10%
  - id: my_black
    red: 0%
    green: 0%
    blue: 0%
  - id: my_white
    red: 100%
    green: 100%
    blue: 100%

font:
## Font needs to be monospace!
  - file: "fonts/iosevka.ttf"
    id: large_font
    size: ${large_font_size}
    glyphs: '*/\$#<>!"%()[]+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz&êÊîÎâÂôÔéÉíÍáÁóÓëËüÜïÏṣṢ'''
  - file: "fonts/iosevka.ttf"
    id: medium_font
    size: ${medium_font_size}
    glyphs: '*/\$#<>!"%()[]+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz&êÊîÎâÂôÔéÉíÍáÁóÓëËüÜïÏṣṢ'''
  - file: "fonts/iosevka.ttf"
    id: small_font
    size: ${small_font_size}
    glyphs: '*/\$#<>!"%()[]+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz&êÊîÎâÂôÔéÉíÍáÁóÓëËüÜïÏṣṢ'''

image:
## You need 2 icons for each, one with a color background, one with black
## todo would be make these material icons or svg
  - file: "images/playWhite.png"
    id: image_play_white
    type: RGB24
  - file: "images/play.png"
    id: image_play
    type: RGB24
  - file: "images/pause.png"
    id: image_pause
    type: RGB24
  - file: "images/pauseWhite.png"
    id: image_pause_white
    type: RGB24
  - file: "images/stop.png"
    id: image_stop
    type: RGB24
  - file: "images/stopWhite.png"
    id: image_stop_white
    type: RGB24
  - file: "images/sleepWhite.png"
    id: image_sleep_white
    type: RGB24
  - file: "images/sleep.png"
    id: image_sleep
    type: RGB24
  - file: "images/shuffle.png"
    id: image_shuffle
    type: RGB24
  - file: "images/shuffleDisabled.png"
    id: image_shuffle_disabled
    type: RGB24
  - file: "images/volumeLow.png"
    id: image_volume_low
    type: RGB24
  - file: "images/volumeHigh.png"
    id: image_volume_high
    type: RGB24
    
globals:
## Size of the large font above
  - id: large_font_size
    type: int
    restore_value: no
    initial_value: ${large_font_size}
    
## Size of the medium font above
  - id: medium_font_size
    type: int
    restore_value: no
    initial_value: ${medium_font_size}
    
## Size of the small font above
  - id: small_font_size
    type: int
    restore_value: no
    initial_value: ${small_font_size}
    
## Height / width ratio of the monospace font used
  - id: font_size_width_ratio
    type: double
    restore_value: no
    initial_value: "0.6"
    
## Status bar height
  - id: header_height
    type: int
    restore_value: no
    initial_value: ${header_height}
    
## Global margin size
  - id: margin_size
    type: int
    restore_value: no
    initial_value: ${margin_size}
    
## Scrollbar total width
  - id: scroll_bar_width
    type: int
    restore_value: no
    initial_value: ${scroll_bar_width}
    
## Volume bar and media duration bar margin
  - id: bottom_bar_margin
    type: int
    restore_value: no
    initial_value: ${bottom_bar_margin}
    
## Height and width of the icons used in px
  - id: icon_size
    type: int
    restore_value: no
    initial_value: "12"
    
## Max lines on now playing screen before truncating happens
  - id: now_playing_max_lines
    type: int
    restore_value: no
    initial_value: ${now_playing_max_lines}
    
## Draw buttons in now playing menu for 3 button devices
  - id: draw_now_playing_menu
    type: bool
    restore_value: no
    initial_value: ${draw_now_playing_menu}
    
## Draw battery icon if battery level is supported
  - id: draw_battery_level
    type: bool
    restore_value: no
    initial_value: ${draw_battery_level}
    
## Draw shuffle icon if shuffle is disabled
  - id: draw_shuffle_disabled
    type: bool
    restore_value: no
    initial_value: ${draw_shuffle_disabled}
    
## Customize device boot name
  - id: boot_device_name
    type: std::string
    restore_value: no
    initial_value: ${boot_name}

interval:
  - interval: 1s
    then:
    - lambda: |-
        idleTick();
  - interval: 0.3s
    then:
    - lambda: |-
        activeTick();

deep_sleep:
  id: deep_sleep_1

binary_sensor:
  - platform: status
    name: ${boot_name}Node Status"
    id: system_status

api:
  services:
    - service: goto_screen
      variables:
        screen_name: string
      then:
      - lambda: |-
          goToScreenFromString(screen_name);

time:
  - platform: homeassistant
    id: esptime
