binary_sensor:
  - platform: gpio
    pin:
      number: GPIO37
      inverted: true
    name: Button A
    on_click:
      min_length: 5ms
      max_length: 350ms
      then:
      - lambda: |-
          id(homeThingMenu)->buttonPressSelect();
    on_multi_click:
    - timing:
        - ON for at least 0.5s
      then:
      - lambda: |-
          id(homeThingMenu)->buttonPressSelectHold();
    - timing:
        - ON for at least 3s
      then:
      - lambda: |-
          id(restart_switch)->toggle();
    on_release:
      then:
        - light.turn_off: led1
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: Button B
    on_press:
      then:
        lambda: |-
          id(homeThingMenu)->buttonPressWakeUpDisplay();
          id(homeThingMenu)->topMenu(); 
          id(led1).turn_on().set_transition_length(0).perform();
    on_release:
      then:
        - light.turn_off: led1
