sensor:
  ## Rotary
    - platform: rotary_encoder
      filters:
      - throttle: 0.01s
      name: "Rotary Encoder"
      internal: true
      pin_a:
        number: 21
        mode:
          input: true
          pullup: true
      pin_b:
        number: 22
        mode:
          input: true
          pullup: true
      id: rotary
      on_clockwise:
        - lambda: |-
            id(homeThingMenu)->buttonPressWakeUpDisplay();
            id(homeThingMenu)->rotaryScrollClockwise(id(rotary).state);
      on_anticlockwise:
        - lambda: |-
            id(homeThingMenu)->buttonPressWakeUpDisplay();
            id(homeThingMenu)->rotaryScrollCounterClockwise(id(rotary).state);